import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu,X,ArrowDown,Sparkles,ArrowUpRight,ArrowLeft,ExternalLink} from 'lucide-react';
import './styles.css';

const BASE=import.meta.env.BASE_URL.replace(/\/$/,'');
const assetPath=x=>`${import.meta.env.BASE_URL}projects/${x}`;
const getSlug=()=>{const p=window.location.pathname.replace(import.meta.env.BASE_URL,'').split('/').filter(Boolean);return p.at(-1)||null;};

const projects=[
 {slug:'aurora-identity',title:'Aurora Identity',category:'Branding',year:'2026',image:assetPath('aurora-real.svg'),desc:'A premium visual identity study built around contrast, restraint and a luminous monogram.',client:'Concept Project',tools:['Adobe Illustrator','Brand Strategy','Art Direction'],overview:'A fictional identity exercise exploring how a small visual system can feel premium, memorable and adaptable across print and digital.',challenge:'Create a brand language that feels distinctive without becoming visually noisy.',direction:'A dark editorial foundation is paired with antique gold geometry, generous negative space and a single recognizable monogram.',process:['Research & mood direction','Identity sketching','Logo refinement','Mockup & presentation'],outcome:'A compact identity system designed to scale from a signature mark to a complete presentation.',gallery:[assetPath('aurora-real.svg'),assetPath('stories-real.svg')]},
 {slug:'glow-campaign',title:'Glow Campaign',category:'Social Media',year:'2026',image:assetPath('glow-real.svg'),desc:'A social campaign concept combining editorial typography, product storytelling and scroll-stopping composition.',client:'Concept Campaign',tools:['Social Strategy','Adobe Illustrator','Content Design'],overview:'A campaign system for a modern lifestyle brand, built to turn individual posts into one recognizable visual story.',challenge:'Make social content feel premium while keeping the message immediately understandable in a fast-moving feed.',direction:'Large type, warm contrast, device mockups and repeatable composition rules create a consistent campaign language.',process:['Campaign idea','Content pillars','Key visual','Post system'],outcome:'A reusable social framework that can expand into carousels, stories and short-form video.',gallery:[assetPath('glow-real.svg'),assetPath('care-real.svg')]},
 {slug:'serene-spaces',title:'Serene Spaces',category:'Graphic Design',year:'2026',image:assetPath('serene-real.svg'),desc:'An interior-design presentation concept turning architecture, material and light into a visual story.',client:'Concept Interior Project',tools:['Adobe InDesign','Adobe Illustrator','Layout Design'],overview:'A portfolio presentation direction for an interior studio where the space remains the hero and typography quietly supports it.',challenge:'Present architectural detail with enough atmosphere to feel aspirational while remaining clean and credible.',direction:'Warm ivory, deep charcoal and structured grids create a gallery-like presentation system.',process:['Project selection','Visual hierarchy','Grid system','Portfolio composition'],outcome:'A refined presentation language suitable for project sheets, brochures and social content.',gallery:[assetPath('serene-real.svg'),assetPath('stories-real.svg')]},
 {slug:'moments-in-motion',title:'Moments in Motion',category:'Video',year:'2026',image:assetPath('moments-real.svg'),desc:'A cinematic edit direction focused on rhythm, atmosphere, framing and emotional pacing.',client:'Concept Film',tools:['Adobe Premiere Pro','Editing','Sound Design'],overview:'A short-form film concept built around visual rhythm rather than heavy effects, using cuts, pauses and framing to create emotion.',challenge:'Make a short edit feel cinematic within a tight attention window.',direction:'Deep shadows, controlled highlights and intentional pacing create a premium visual rhythm.',process:['Footage selection','Rough cut','Rhythm pass','Color & finishing'],outcome:'A repeatable short-form editing approach for reels, promos and brand films.',gallery:[assetPath('moments-real.svg'),assetPath('elemental-real.svg')]},
 {slug:'elemental-motion',title:'Elemental Motion',category:'Motion',year:'2026',image:assetPath('elemental-real.svg'),desc:'An abstract motion study where particles, rings and light become a visual language.',client:'Motion Study',tools:['Motion Design','Keyframe Animation','Compositing'],overview:'A visual experiment translating a simple symbol into movement, light and depth.',challenge:'Create movement that feels expressive without relying on a large number of assets.',direction:'Circular forms, particle trails and gold light become a small motion vocabulary.',process:['Concept frame','Motion blocking','Particle pass','Polish'],outcome:'A flexible motion language for logo reveals, title cards and promotional transitions.',gallery:[assetPath('elemental-real.svg'),assetPath('aurora-real.svg')]},
 {slug:'digital-dreams',title:'Digital Dreams',category:'AI Creative',year:'2026',image:assetPath('dreams-real.svg'),desc:'An AI-assisted visual experiment exploring surreal portraiture and controlled art direction.',client:'AI Creative Experiment',tools:['AI Image Generation','Prompt Design','Art Direction'],overview:'A controlled AI visual workflow focused on turning a creative idea into a coherent image direction rather than generating random outputs.',challenge:'Keep the visual identity consistent while exploring generative possibilities.',direction:'A restrained palette, defined lighting and repeated composition rules create continuity across concepts.',process:['Prompt architecture','Reference direction','Generation rounds','Selection & refinement'],outcome:'A repeatable AI-assisted workflow for concept exploration and campaign development.',gallery:[assetPath('dreams-real.svg'),assetPath('hero-archive.svg')]},
 {slug:'care-beyond',title:'Care Beyond',category:'Graphic Design',year:'2026',image:assetPath('care-real.svg'),desc:'A healthcare communication concept balancing trust, warmth and contemporary editorial design.',client:'Healthcare Concept',tools:['Campaign Design','Adobe Illustrator','Social Media'],overview:'A healthcare communication concept designed to feel human, clear and trustworthy across campaign touchpoints.',challenge:'Communicate care without falling into generic medical visual language.',direction:'Clean typography, warm ivory surfaces and a restrained clinical symbol create a calmer identity.',process:['Message framing','Visual system','Campaign layouts','Adaptation'],outcome:'A flexible visual direction for hospital campaigns, awareness posts and print collateral.',gallery:[assetPath('care-real.svg'),assetPath('glow-real.svg')]},
 {slug:'visual-stories',title:'Visual Stories',category:'Graphic Design',year:'2026',image:assetPath('stories-real.svg'),desc:'A publication-style art direction study for portfolios, brochures and brand storytelling.',client:'Editorial Concept',tools:['Adobe InDesign','Editorial Design','Typography'],overview:'A magazine-inspired design system for turning projects into readable, visual stories.',challenge:'Balance imagery, typography and information so a portfolio feels designed rather than simply assembled.',direction:'Large editorial headlines, disciplined columns and generous margins create a premium reading experience.',process:['Content mapping','Typography pairing','Grid development','Page sequencing'],outcome:'A reusable editorial framework for brochures, portfolios and case-study documents.',gallery:[assetPath('stories-real.svg'),assetPath('serene-real.svg')]}
];

const cats=['All','Branding','Graphic Design','Social Media','Video','Motion','AI Creative'];
function App(){
 const [loading,setLoading]=useState(true),[menu,setMenu]=useState(false),[filter,setFilter]=useState('All'),[magic,setMagic]=useState(true),[weather,setWeather]=useState('snow'),[route,setRoute]=useState(getSlug());
 useEffect(()=>{const t=setTimeout(()=>setLoading(false),1400);const pop=()=>setRoute(getSlug());window.addEventListener('popstate',pop);return()=>{clearTimeout(t);window.removeEventListener('popstate',pop)}},[]);
 const openProject=p=>{window.history.pushState({},'',`${BASE}/work/${p.slug}`);setRoute(p.slug);window.scrollTo({top:0,behavior:'smooth'});setMenu(false)};
 const home=id=>{window.history.pushState({},'',id?`${BASE}/#${id}`:`${BASE}/`);setRoute(null);setMenu(false);setTimeout(()=>id&&document.getElementById(id)?.scrollIntoView({behavior:'smooth'}),30)};
 if(loading)return <div className="loader"><div className="orbit">KC</div><b>CREATIVE ALCHEMIST</b><small>Design. Motion. Story. Magic.</small></div>;
 const cycleWeather=()=>setWeather(w=>w==='snow'?'storm':w==='storm'?'arcane':w==='arcane'?'off':'snow');
 const project=projects.find(p=>p.slug===route);
 if(route&&project)return <ProjectPage project={project} onHome={home} onProject={openProject} magic={magic} setMagic={setMagic} menu={menu} setMenu={setMenu} weather={weather} setWeather={setWeather} cycleWeather={cycleWeather}/>;
 const shown=filter==='All'?projects:projects.filter(p=>p.category===filter);
 return <div className={(magic?'app magic ':'app ')+`weather-${weather}`}>
  <Atmosphere weather={weather}/>
  <Nav menu={menu} setMenu={setMenu} magic={magic} setMagic={setMagic} weather={weather} setWeather={setWeather} cycleWeather={cycleWeather} onHome={home}/>
  <section id="home" className="hero">
   <div className="hero-ambient"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="hero-haze"/></div>
   <div className="hero-grid"/>
   <div className="hero-copy">
    <div className="hero-kicker"><span>KC</span><b/> CREATIVE ALCHEMIST <em>01 / 07</em></div>
    <h1>KRUNAL<br/><i>CHAUHAN</i></h1>
    <div className="hero-rule"><span>DESIGN</span><b/><span>MOTION</span><b/><span>STORY</span></div>
    <h2>I turn ideas into <span>visual experiences.</span></h2>
    <p className="hero-meta">Graphic Designer · Content Creator · Video Editor · AI Prompt Maker</p>
    <div className="actions"><button className="gold" onClick={()=>home('work')}>EXPLORE THE WORK <ArrowDown size={15}/></button><button className="outline" onClick={()=>home('contact')}>START A PROJECT</button></div>
    <p className="tagline">“Where creativity becomes magic.”</p>
   </div>
   <div className="hero-visual" aria-hidden="true">
    <div className="visual-orbit orbit-a"/><div className="visual-orbit orbit-b"/>
    <div className="visual-frame">
      <div className="visual-image"/>
      <div className="visual-shade"/>
      <div className="visual-spark spark-a">✦</div><div className="visual-spark spark-b">✦</div>
      <div className="visual-label"><span>CREATIVE REALM</span><b>VOL. 01</b></div>
    </div>
    <div className="visual-caption">ART DIRECTION / VISUAL STORYTELLING</div>
   </div>
   <div className="hero-bottom"><span>SCROLL TO EXPLORE</span><b/><small>07.02.1998 — KC</small></div>
  </section>
  <Section id="about" eyebrow="THE WIZARD BEHIND THE WORK" title={<>Creative thinking,<br/><i>visual alchemy.</i></>}><div className="about"><div className="portrait"><span>KC</span><small>CREATIVE ALCHEMIST</small></div><div><p className="lead">I'm Krunal Chauhan — a creative professional working across graphic design, social media, video editing, branding, and AI-powered creative workflows.</p><p className="muted">I combine design thinking, visual storytelling, and emerging AI tools to turn ideas into engaging digital experiences.</p><div className="chips"><span>Creative Designer</span><span>Content Creator</span><span>Video Editor</span><span>AI Prompt Maker</span></div></div></div></Section>
  <section className="featured section"><div className="featured-head"><div><p className="eyebrow">THE ARCHIVES</p><h2 className="title">Featured <i>Work.</i></h2></div><button className="text-link" onClick={()=>home('work')}>VIEW ALL PROJECTS <ArrowUpRight size={15}/></button></div><p className="featured-intro">A collection of visual experiments, campaigns, and creative work.</p><div className="featured-grid">{projects.map((p,i)=><article className="featured-card" key={p.slug} onClick={()=>openProject(p)}><div className="featured-art"><img src={p.image} alt={p.title}/><span>0{i+1}</span></div><div className="featured-info"><small>{p.category}</small><h3>{p.title}</h3><span>{p.year}<ArrowUpRight size={13}/></span></div></article>)}</div><div className="values"><div><b>✦</b><strong>DESIGN</strong><span>Ideas into identity.</span></div><div><b>○</b><strong>CREATE</strong><span>Concepts into content.</span></div><div><b>△</b><strong>COLLABORATE</strong><span>Visions into reality.</span></div><div><b>∞</b><strong>INSPIRE</strong><span>Creativity without limits.</span></div><blockquote>“Design is a different kind of magic.”<small>— KC</small></blockquote></div></section>\n  <Section id="work" eyebrow="THE ARCHIVES" title={<>Selected <i>work.</i></>}><div className="archive-head"><p className="muted">Temporary concept projects are installed for now. Replace each cover with your real work later without changing the case-study structure.</p><div className="filters">{cats.map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="grid">{shown.map(p=><article className="card" key={p.title} onClick={()=>openProject(p)}><div className="art"><img src={p.image} alt={p.title}/><span>0{projects.indexOf(p)+1}</span><b>{p.category}</b></div><div className="card-copy"><div><h3>{p.title}</h3><p>{p.desc}</p></div><button aria-label={'Open '+p.title} onClick={e=>{e.stopPropagation();openProject(p)}}><ArrowUpRight size={18}/></button></div><small className="year">{p.year}</small></article>)}</div></Section>
  <Section id="services" eyebrow="THE SPELLBOOK" title={<>Creative <i>services.</i></>}><div className="grid services">{['Graphic Design','Branding','Social Media','Video Editing','Motion Graphics','AI Creative'].map((x,i)=><article className="service" key={x}><small>0{i+1}</small><h3>{x}</h3><p className="muted">Creative services for brands that want to stand out through strong visual communication.</p></article>)}</div></Section>
  <Section id="experience" eyebrow="THE JOURNEY" title={<>Experience & <i>evolution.</i></>}><div className="timeline"><div><p>2025 — PRESENT</p><h3>Social Media / Creative — Welcare Hospital</h3><span>Design · Content · Campaigns · Visual Communication</span></div><div><p>PREVIOUS EXPERIENCE</p><h3>Creative / Design — PB Distributor</h3><span>Graphic Design · Visual Content · Brand Support</span></div></div></Section>
  <Section id="skills" eyebrow="THE ARSENAL" title={<>Tools of the <i>craft.</i></>}><div className="skills">{['Adobe Illustrator','Adobe Premiere Pro','Adobe InDesign','Video Editing','Graphic Design','Branding','Social Media Marketing','Content Creation','AI Creative Tools','Prompt Engineering','Campaign Design','Visual Storytelling'].map(x=><div key={x}>✦ {x}</div>)}</div></Section>
  <Section id="contact" eyebrow="SEND A MESSAGE" title={<>LET'S CREATE<br/><i>SOMETHING MAGICAL.</i></>}><div className="contact"><div><p className="lead">Have an idea, campaign, or project in mind? Let's turn it into something people remember.</p><p className="muted">Contact integration will be connected once your preferred email/backend is selected.</p></div><div className="form"><input placeholder="Name"/><input placeholder="Email"/><input placeholder="Phone"/><input placeholder="Project Type"/><input placeholder="Budget"/><textarea placeholder="Tell me about your project..."/><button className="gold" onClick={()=>alert('Contact integration is not configured yet. No message was sent.')}>SEND MESSAGE</button></div></div></Section>
  <Footer/>
 </div>
}

function Atmosphere({weather}){const flakes=Array.from({length:70},(_,i)=>i);return <div className={`atmosphere ${weather}`} aria-hidden="true"><div className="rain-layer"/><div className="snow-layer">{flakes.map(i=><i key={i} style={{'--i':i,'--x':`${(i*37)%100}%`,'--d':`${4+(i%7)}s`,'--s':`${2+(i%5)}px`,'--delay':`${-(i%9)}s`}}/> )}</div><div className="lightning l1"/><div className="lightning l2"/><div className="magic-dust"/></div>}
function Nav({menu,setMenu,magic,setMagic,weather='off',setWeather=()=>{},cycleWeather=()=>{},onHome,detail=false}){return <nav><button className="brand" onClick={()=>onHome()}><strong>KC</strong><small>CREATIVE ALCHEMIST</small></button><div className={menu?'links open':'links'}>{['home','about','work','services','experience','skills','contact'].map(x=><button key={x} onClick={()=>onHome(x)}>{x}</button>)}</div><div className="tools"><div className="weather-switcher">{[["snow","❄","SNOW"],["storm","♨","STORM"],["arcane","✦","ARCANE"],["off","✧","OFF"]].map(([mode,icon,label])=><button key={mode} className={weather===mode?"selected":""} onClick={()=>{setWeather(mode);setMagic(mode!=="off")}} title={label}><span>{icon}</span>{label}</button>)}</div><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav>}

function ProjectPage({project,onHome,onProject,magic,setMagic,menu,setMenu,weather='off',setWeather=()=>{},cycleWeather=()=>{}}){
 const related=projects.filter(p=>p.slug!==project.slug&&p.category===project.category).slice(0,2);
 const fallback=projects.filter(p=>p.slug!==project.slug&&!related.includes(p)).slice(0,2-related.length);
 const relatedAll=[...related,...fallback];
 return <div className={magic?'app magic':'app'}>
  <Nav menu={menu} setMenu={setMenu} magic={magic} setMagic={setMagic} weather={weather} setWeather={setWeather} cycleWeather={cycleWeather} onHome={onHome} detail/>
  <main className="project-page">
   <div className="project-top"><button className="back-link" onClick={()=>onHome('work')}><ArrowLeft size={15}/> BACK TO ARCHIVES</button><span>{project.category} · {project.year}</span></div>
   <section className="project-hero"><div><p className="eyebrow">{project.category.toUpperCase()}</p><h1>{project.title}</h1><p className="project-intro">{project.desc}</p></div><img src={project.image} alt={project.title}/></section>
   <section className="case-grid"><div><p className="eyebrow">OVERVIEW</p><p className="case-lead">{project.overview}</p></div><div className="meta-card"><div><span>CLIENT</span><b>{project.client}</b></div><div><span>YEAR</span><b>{project.year}</b></div><div><span>CATEGORY</span><b>{project.category}</b></div></div></section>
   <section className="case-section"><p className="eyebrow">THE CHALLENGE</p><h2>What needed to <i>change.</i></h2><p>{project.challenge}</p></section>
   <section className="case-section direction"><div><p className="eyebrow">CREATIVE DIRECTION</p><h2>A visual language with <i>intention.</i></h2><p>{project.direction}</p></div><div className="direction-orb"><span>✦</span></div></section>
   <section className="case-section"><p className="eyebrow">THE PROCESS</p><h2>From idea to <i>execution.</i></h2><div className="process-grid">{project.process.map((step,i)=><div key={step}><small>0{i+1}</small><h3>{step}</h3><span>Creative phase</span></div>)}</div></section>
   <section className="gallery-section"><div className="gallery-head"><div><p className="eyebrow">THE GALLERY</p><h2>Built to <i>be seen.</i></h2></div><p className="muted">A temporary visual gallery for the concept. Your real project images can replace these assets later.</p></div><div className="project-gallery">{project.gallery.map((img,i)=><figure key={img+i}><img src={img} alt={`${project.title} visual ${i+1}`}/><figcaption>0{i+1} / VISUAL STUDY</figcaption></figure>)}</div></section>
   <section className="case-section outcome"><p className="eyebrow">THE OUTCOME</p><h2>Designed for <i>impact.</i></h2><p>{project.outcome}</p><div className="tool-row">{project.tools.map(t=><span key={t}>{t}</span>)}</div></section>
   <section className="related"><p className="eyebrow">RELATED PROJECTS</p><h2>Continue through <i>the archives.</i></h2><div className="grid">{relatedAll.map(p=><article className="card" key={p.slug} onClick={()=>onProject(p)}><div className="art"><img src={p.image} alt={p.title}/><b>{p.category}</b></div><div className="card-copy"><div><h3>{p.title}</h3><p>{p.desc}</p></div><ArrowUpRight size={18}/></div></article>)}</div></section>
   <section className="project-cta"><p className="eyebrow">START A PROJECT</p><h2>Let's create something <i>magical.</i></h2><button className="gold" onClick={()=>onHome('contact')}>START A PROJECT <ExternalLink size={15}/></button></section>
  </main>
  <Footer/>
 </div>
}

function Section({id,eyebrow,title,children}){return <section id={id} className="section"><p className="eyebrow">{eyebrow}</p><h2 className="title">{title}</h2>{children}</section>}
function Footer(){return <footer><strong>KC</strong><span>Where Creativity Becomes Magic.</span><small>© 2026 Krunal Chauhan · Creative Alchemist</small></footer>}
createRoot(document.getElementById('root')).render(<App/>);